## Awkable

Load and convert data to a form suitable for Alex's `awk` based scripts

In [1]:
import pandas as pd
from igndata import load
import matplotlib.pyplot as plt

In [2]:
 df = pd.read_csv('./lapalma_ign.csv')
df['Date'] = pd.to_datetime(df.Date, dayfirst=True)
df = df.sort_values(by=['Date', 'Time'], ascending=[False,False])
df.head()

,Event,Date,Time,Latitude,Longitude,Depth(km),Intensity,Magnitude,Type Mag,Location,DateTime,Timestamp,Swarm,Phase
11346,es2022sadhg,2022-09-14,03:58:59,28.5415,-17.8770,13.0,,1.1,4,NW FUENCALIENTE DE LA PALMA.IL,2022-09-14 03:58:59,1663127939000000000,NaN,4
11345,es2022rzzlw,2022-09-14,02:03:08,28.5421,-17.8763,11.0,,1.1,4,NW FUENCALIENTE DE LA PALMA.IL,2022-09-14 02:03:08,1663120988000000000,NaN,4
11344,es2022rzywe,2022-09-14,01:44:52,28.5624,-17.8460,14.0,II,2.0,4,N FUENCALIENTE DE LA PALMA.ILP,2022-09-14 01:44:52,1663119892000000000,NaN,4
11343,es2022rzysl,2022-09-14,01:40:30,28.5749,-17.8699,13.0,,0.9,4,N FUENCALIENTE DE LA PALMA.ILP,2022-09-14 01:40:30,1663119630000000000,NaN,4
11342,es2022rzwcc,2022-09-14,00:20:51,28.5638,-17.8800,10.0,,1.0,4,NW FUENCALIENTE DE LA PALMA.IL,2022-09-14 00:20:51,1663114851000000000,NaN,4

In [3]:
df["id"] = df["Event"]
df["yyyymmdd"] = df["Date"].dt.strftime("%Y%m%d")
df["hhmmss"] = pd.to_datetime(df["Time"]).dt.strftime("%H%M%S.000")
df["zero"] = 0
df.head()

,Event,Date,Time,Latitude,Longitude,Depth(km),Intensity,Magnitude,Type Mag,Location,DateTime,Timestamp,Swarm,Phase,id,yyyymmdd,hhmmss,zero
11346,es2022sadhg,2022-09-14,03:58:59,28.5415,-17.8770,13.0,,1.1,4,NW FUENCALIENTE DE LA PALMA.IL,2022-09-14 03:58:59,1663127939000000000,NaN,4,es2022sadhg,20220914,035859.000,0
11345,es2022rzzlw,2022-09-14,02:03:08,28.5421,-17.8763,11.0,,1.1,4,NW FUENCALIENTE DE LA PALMA.IL,2022-09-14 02:03:08,1663120988000000000,NaN,4,es2022rzzlw,20220914,020308.000,0
11344,es2022rzywe,2022-09-14,01:44:52,28.5624,-17.8460,14.0,II,2.0,4,N FUENCALIENTE DE LA PALMA.ILP,2022-09-14 01:44:52,1663119892000000000,NaN,4,es2022rzywe,20220914,014452.000,0
11343,es2022rzysl,2022-09-14,01:40:30,28.5749,-17.8699,13.0,,0.9,4,N FUENCALIENTE DE LA PALMA.ILP,2022-09-14 01:40:30,1663119630000000000,NaN,4,es2022rzysl,20220914,014030.000,0
11342,es2022rzwcc,2022-09-14,00:20:51,28.5638,-17.8800,10.0,,1.0,4,NW FUENCALIENTE DE LA PALMA.IL,2022-09-14 00:20:51,1663114851000000000,NaN,4,es2022rzwcc,20220914,002051.000,0

In [4]:
def write_to_awk(df, filename):
    df.to_csv(filename, index=False, 
              columns=['yyyymmdd','hhmmss','Latitude','Longitude','Depth(km)','Magnitude','zero','zero','zero','zero','id','zero','Swarm', 'Phase'],
              header=["yyyymmdd","hhmmss.sss","lat","lon","depth","Mw","q1","q2","nSta","nPha","ID","sourceType", "Swarm", "Phase"])

In [5]:
df_ign = df
df_ign_early = df_ign[df_ign['Date'] < '2021-09-11']
df_ign_pre = df_ign[(df_ign['Date'] >= '2021-09-11')&(df_ign['Date'] < '2021-09-19')]
df_ign_phase1 = df_ign[(df_ign['Date'] >= '2021-09-11')&(df_ign['Date'] < '2021-10-01')]
df_ign_phase2 = df_ign[(df_ign['Date'] >= '2021-10-01')&(df_ign['Date'] < '2021-12-01')]
df_ign_phase3 = df_ign[(df_ign['Date'] >= '2021-12-01')&(df_ign['Date'] <= '2021-12-31')]

In [6]:
write_to_awk(df_ign, "./exports/awk_lapalma_ign.csv")
write_to_awk(df_ign_early, "./exports/awk_lapalma_ign_early.csv")
write_to_awk(df_ign_phase1, "./exports/awk_lapalma_ign_phase1.csv")
write_to_awk(df_ign_phase2, "./exports/awk_lapalma_ign_phase2.csv")
write_to_awk(df_ign_phase3, "./exports/awk_lapalma_ign_phase3.csv")